#!/bin/bash -x
#SBATCH --partition=debug
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH -o ferret-compile.out
#SBATCH -e ferret-compile.out
#SBATCH --exclude=cn[01-64,105-320]
#SBATCH --time=00:30:00


echo > ferret-compile.out

source /apps2/Modules/default/init/bash
module purge 
module load tcl/8.6.6.8606 sqlite/3.18.0 zlib/1.2.11 openssl/1.0.2o libcurl/7.60.0 gcc/5.4.0-alt git/2.7.2 mpi/openmpi/1.10.3 cuda/7.5 python/3.7.3 petsc/3.8.4-gcc-mpi libxml2/2.9.3-gcc boost/1.61.0-gcc-mpi hdf5/1.8.12 petsc/3.8.4-gcc-mpi hwloc/5.6.1 

export \
    CPPFLAGS=$(echo "-I${INCLUDE//:/ -I}") -g \
    LDFLAGS=$(echo "-L${LD_LIBRARY_PATH//:/ -L}") \
#    MOOSE_JOBS=1 \
    MOOSE_JOBS=$SLURM_CPUS_ON_NODE \
    BOOST_ROOT=/apps2/boost/1.61.0-gcc-mpi \
    HDF5_DIR=/apps2/hdf5/1.8.12 \
    PETSC_DIR=/apps2/petsc/3.8.4-gcc-mpi

export \
    CC=mpicc \
    CXX=mpicxx \
    EXTERNAL_FLAGS=-Wl,-rpath,/apps2/gcc/5.4.0-alt/lib64 \
    FC=mpif90 \
    F90=mpif90 \
    F77=mpif77

cd /shared/sergelab/Spring2020/projects/ferret
./configure --prefix=/shared/sergelab/Spring2020/projects/ferret
make -j 4  MOOSE_DIR=/shared/sergelab/Spring2020/projects/moose
./run_tests -j 4
