#!/bin/bash -x

#SBATCH --partition=SandyBridgePriority
#SBATCH --ntasks=16
#SBATCH -o moose-compile.out
#SBATCH -e moose-compile.out
#SBATCH --exclude=cn[01-64,105-320]


echo > moose-compile.out

source /apps2/Modules/default/init/bash


module purge 
module load zlib/1.2.11 openssl/1.0.2o libcurl/7.60.0 gcc/5.4.0-alt git/2.7.2 mpi/openmpi/1.10.3 cuda/7.5 python/2.7.6 libxml2/2.9.3-gcc boost/1.61.0-gcc-mpi hdf5/1.8.12 petsc/3.8.4-gcc-mpi hwloc/5.6.1 

export \
    CPPFLAGS=$(echo "-I${INCLUDE//:/ -I}") -g \
    LDFLAGS=$(echo "-L${LD_LIBRARY_PATH//:/ -L}") \
#    MOOSE_JOBS=1 \
    MOOSE_JOBS=$SLURM_CPUS_ON_NODE \
    BOOST_ROOT=/apps2/boost/1.61.0-gcc-mpi \
    HDF5_DIR=/apps2/hdf5/1.8.12 \
    PETSC_DIR=/apps2/petsc/3.8.4-gcc-mpi

export \
    CC=mpicc \
    CXX=mpicxx \
    FC=mpifort \
    F90=mpif90

/shared/sergelab/testprojects/moose/scripts/update_and_rebuild_libmesh.sh

cd /shared/sergelab/testprojects/moose/test
make --jobs=16
./run_tests -j 16
