#!/bin/bash


#SBATCH --ntasks-per-node=16
#SBATCH -N 1
#SBATCH --mail-user=john.mangeri@uconn.edu
#SBATCH --mail-type=ALL
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.out

mpirun -v ./ferret-opt -i newsingle_sphere-1.i
