#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=200:00:00
#PBS -N PZTtest
#PBS -q msd
#PBS -M john.mangeri@uconn.edu

N_C=`wc -l $PBS_NODEFILE | gawk '//{print $1}'`       # number of CPUs or cores


cd /lcrc/project/Meso/projects/ferret

date

mpiexec -np ${N_C} ./ferret-opt -i PZTepitaxy_09_20_10_10.i  > PZTepitaxy_09_20_10_10-log

date

