#!/bin/bash

#SBATCH -p Serge
#SBATCH --ntasks-per-node=16
#SBATCH -N 2
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.out

for ((i=0;i<10;i++))
  for ((j=0;j<10;j++))
    do
    mpirun -v ./ferret-opt -i newcoupledTests-$i-$j.i
	  done
