#!/bin/bash

#SBATCH -p Serge
#SBATCH --ntasks-per-node=16
#SBATCH -N 3
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.out

mpirun -v ./ferret-opt -i newcoupledTests-1-0.i
mpirun -v ./ferret-opt -i newcoupledTests-7-1.i
mpirun -v ./ferret-opt -i newcoupledTests-7-2.i
mpirun -v ./ferret-opt -i newcoupledTests-7-3.i
mpirun -v ./ferret-opt -i newcoupledTests-7-4.i
mpirun -v ./ferret-opt -i newcoupledTests-7-5.i
mpirun -v ./ferret-opt -i newcoupledTests-7-6.i
mpirun -v ./ferret-opt -i newcoupledTests-7-7.i
mpirun -v ./ferret-opt -i newcoupledTests-7-8.i
mpirun -v ./ferret-opt -i newcoupledTests-7-9.i
mpirun -v ./ferret-opt -i newcoupledTests-7-10.i
mpirun -v ./ferret-opt -i newcoupledTests-7-11.i
