#!/bin/bash

#SBATCH -p Serge
#SBATCH --ntasks-per-node=16
#SBATCH -N 3
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.out

mpirun -v ./ferret-opt -i newcoupledTests-2-0.i
mpirun -v ./ferret-opt -i newcoupledTests-2-1.i
mpirun -v ./ferret-opt -i newcoupledTests-2-2.i
mpirun -v ./ferret-opt -i newcoupledTests-2-3.i
mpirun -v ./ferret-opt -i newcoupledTests-2-4.i
mpirun -v ./ferret-opt -i newcoupledTests-2-5.i
mpirun -v ./ferret-opt -i newcoupledTests-2-6.i
mpirun -v ./ferret-opt -i newcoupledTests-2-7.i
mpirun -v ./ferret-opt -i newcoupledTests-2-8.i
mpirun -v ./ferret-opt -i newcoupledTests-2-9.i
