#!/bin/bash

#SBATCH -p Serge
#SBATCH --ntasks-per-node=16
#SBATCH -N 3
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.out

mpirun -v ./ferret-opt -i newcoupledTests-3-0.i
mpirun -v ./ferret-opt -i newcoupledTests-3-1.i
mpirun -v ./ferret-opt -i newcoupledTests-3-2.i
mpirun -v ./ferret-opt -i newcoupledTests-3-3.i
mpirun -v ./ferret-opt -i newcoupledTests-3-4.i
mpirun -v ./ferret-opt -i newcoupledTests-3-5.i
mpirun -v ./ferret-opt -i newcoupledTests-3-6.i
mpirun -v ./ferret-opt -i newcoupledTests-3-7.i
mpirun -v ./ferret-opt -i newcoupledTests-3-8.i
mpirun -v ./ferret-opt -i newcoupledTests-3-9.i
