#!/bin/bash

#SBATCH -p Serge
#SBATCH --ntasks-per-node=16
#SBATCH -N 3
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.out

mpirun -v ./ferret-opt -i newcoupledTests-4-0.i
mpirun -v ./ferret-opt -i newcoupledTests-4-1.i
mpirun -v ./ferret-opt -i newcoupledTests-4-2.i
mpirun -v ./ferret-opt -i newcoupledTests-4-3.i
mpirun -v ./ferret-opt -i newcoupledTests-4-4.i
mpirun -v ./ferret-opt -i newcoupledTests-4-5.i
mpirun -v ./ferret-opt -i newcoupledTests-4-6.i
mpirun -v ./ferret-opt -i newcoupledTests-4-7.i
mpirun -v ./ferret-opt -i newcoupledTests-4-8.i
mpirun -v ./ferret-opt -i newcoupledTests-4-9.i
