#!/bin/bash

#SBATCH -p Serge
#SBATCH --ntasks-per-node=16
#SBATCH -N 3
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.out


mpirun -v ./ferret-opt -i newcoupledTests-9-0.i
mpirun -v ./ferret-opt -i newcoupledTests-9-1.i
mpirun -v ./ferret-opt -i newcoupledTests-9-2.i
mpirun -v ./ferret-opt -i newcoupledTests-9-3.i
mpirun -v ./ferret-opt -i newcoupledTests-9-4.i
mpirun -v ./ferret-opt -i newcoupledTests-9-5.i
mpirun -v ./ferret-opt -i newcoupledTests-9-6.i
mpirun -v ./ferret-opt -i newcoupledTests-9-7.i
mpirun -v ./ferret-opt -i newcoupledTests-9-8.i
mpirun -v ./ferret-opt -i newcoupledTests-9-9.i
