#!/bin/bash

#SBATCH -p Serge
#SBATCH --ntasks-per-node=16
#SBATCH -N 13
#SBATCH --mail-user=john.mangeri@uconn.edu
#SBATCH --mail-type=ALL
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.out

mpirun -v ./ferret-opt -i newcoupledTests-5-0.i
mpirun -v ./ferret-opt -i newcoupledTests-5-1.i
mpirun -v ./ferret-opt -i newcoupledTests-5-2.i
mpirun -v ./ferret-opt -i newcoupledTests-5-3.i
mpirun -v ./ferret-opt -i newcoupledTests-5-4.i
mpirun -v ./ferret-opt -i newcoupledTests-5-5.i
mpirun -v ./ferret-opt -i newcoupledTests-5-6.i
