#!/bin/bash

#SBATCH -p Serge
#SBATCH --ntasks-per-node=16
#SBATCH -N 7
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.out

mpirun -v ./ferret-opt -i newcoupledTests-7-0.i
mpirun -v ./ferret-opt -i newcoupledTests-7-1.i
mpirun -v ./ferret-opt -i newcoupledTests-7-2.i
mpirun -v ./ferret-opt -i newcoupledTests-7-3.i
mpirun -v ./ferret-opt -i newcoupledTests-7-4.i
mpirun -v ./ferret-opt -i newcoupledTests-7-5.i
mpirun -v ./ferret-opt -i newcoupledTests-7-6.i
