/**
   This file is part of FERRET, an add-on module for MOOSE

   FERRET is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) a___ny later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT A___ny WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU General Public License for _More details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   For help with FERRET please contact J. _Mangeri <john.mangeri@uconn.edu>
   and be sure to track new changes at bitbucket.org/mesoscience/ferret

**/

#include "AnisotropyUSLLG.h"
#include "libmesh/utility.h"

registerMooseObject("FerretApp", AnisotropyUSLLG);

template<>
InputParameters validParams<AnisotropyUSLLG>()
{
  InputParameters params = validParams<Kernel>();
  params.addClassDescription("Calculates a residual contribution for the magnetic anisotropy energy.");
  params.addRequiredParam<unsigned int>("component", "An integer corresponding to the direction the variable this kernel acts in. (0 for theta, 1 for phi)");
  params.addRequiredCoupledVar("azimuth_phi", "The azimuthal component of the constrained magnetic vector");
  params.addRequiredCoupledVar("polar_theta", "The polar component of the constrained magnetic vector");
  params.addRequiredParam<Real>("alpha", "the damping coefficient in the LLG equation");
  params.addRequiredParam<Real>("K1", "K1");
  params.addRequiredParam<Real>("K2", "K2");
  params.addRequiredParam<Real>("nx", "nx");
  params.addRequiredParam<Real>("ny", "ny");
  params.addRequiredParam<Real>("nz", "nz");
  params.addRequiredParam<Real>("g0", "g0");
  params.addRequiredParam<Real>("Ms", "Ms");
  params.addRequiredParam<Real>("mu0", "mu0");
  return params;
}

AnisotropyUSLLG::AnisotropyUSLLG(const InputParameters & parameters)
  :Kernel(parameters),
  _component(getParam<unsigned int>("component")),
  _azimuth_phi_var(coupled("azimuth_phi")),
  _polar_theta_var(coupled("polar_theta")),
  _azimuth_phi(coupledValue("azimuth_phi")),
  _polar_theta(coupledValue("polar_theta")),
  _azimuth_phi_grad(coupledGradient("azimuth_phi")),
  _polar_theta_grad(coupledGradient("polar_theta")),
  _alpha(getParam<Real>("alpha")),
  _K1(getParam<Real>("K1")),
  _K2(getParam<Real>("K2")),
  _nx(getParam<Real>("nx")),
  _ny(getParam<Real>("ny")),
  _nz(getParam<Real>("nz")),
  _g0(getParam<Real>("g0")),
  _Ms(getParam<Real>("Ms")),
  _mu0(getParam<Real>("mu0"))
{
}

Real
AnisotropyUSLLG::computeQpResidual()
{
  if (_component == 0)
  {
    return ((_g0*(1.0/std::sin(_polar_theta[_qp]))*((-2*_ny*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
       (2*_nx*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
       _alpha*((2*_test[_i][_qp]*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
          std::cos(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
             (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
             (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)));
  }
  else if (_component == 1)
  {
    return ((_g0*(1.0/std::sin(_polar_theta[_qp]))*std::sin(_azimuth_phi[_qp])*((2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
        (2*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        _alpha*((2*_nx*_test[_i][_qp]*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
           std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)) - 
   (_g0*std::cos(_azimuth_phi[_qp])*(1.0/std::sin(_polar_theta[_qp]))*((-2*_nx*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        (2*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        _alpha*((2*_ny*_test[_i][_qp]*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
           std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)));
  }
  else
    return 0.0;
}

Real
AnisotropyUSLLG::computeQpJacobian()
{
  if (_component == 0)
  {
    return (-((_g0*_phi[_j][_qp]*(std::cos(_polar_theta[_qp])/std::sin(_polar_theta[_qp]))*(1.0/std::sin(_polar_theta[_qp]))*((-2*_ny*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
          (2*_nx*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
          _alpha*((2*_test[_i][_qp]*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
             std::cos(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
                (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
                (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha))) + 
   (_g0*(1.0/std::sin(_polar_theta[_qp]))*((-8*_K2*_ny*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
        (8*_K2*_nx*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
        (2*_ny*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        (2*_nx*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
        (2*_ny*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        (2*_nx*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_polar_theta[_qp])*std::sin(_azimuth_phi[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        _alpha*((8*_K2*_ny*_test[_i][_qp]*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
           (2*_test[_i][_qp]*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
           _phi[_j][_qp]*std::sin(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms) + 
           std::cos(_polar_theta[_qp])*((-8*_K2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (8*_K2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (8*_K2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_nx*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_polar_theta[_qp])*std::sin(_azimuth_phi[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
              (2*_phi[_j][_qp]*_test[_i][_qp]*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)));
  }
  else if (_component == 1)
  {
    return ((_g0*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp])*(1.0/std::sin(_polar_theta[_qp]))*((2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
        (2*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        _alpha*((2*_nx*_test[_i][_qp]*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
           std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)) - 
   (_g0*std::cos(_azimuth_phi[_qp])*(1.0/std::sin(_polar_theta[_qp]))*((-8*_K2*_nx*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
        (8*_K2*_ny*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
        (2*_nx*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        (2*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
        (2*_phi[_j][_qp]*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        _alpha*((8*_K2*_ny*_test[_i][_qp]*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
           (2*_ny*_test[_i][_qp]*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
           std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-8*_K2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (8*_K2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (8*_K2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
              (2*_nx*_phi[_j][_qp]*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms) + 
           _phi[_j][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)) + 
   (_g0*_phi[_j][_qp]*(1.0/std::sin(_polar_theta[_qp]))*std::sin(_azimuth_phi[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        (2*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        _alpha*((2*_ny*_test[_i][_qp]*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
           std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)) + 
   (_g0*(1.0/std::sin(_polar_theta[_qp]))*std::sin(_azimuth_phi[_qp])*((8*_K2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
        (8*_K2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
        (2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
        (2*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
        (2*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        _alpha*((8*_K2*_nx*_test[_i][_qp]*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
           (2*_nx*_test[_i][_qp]*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
           std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-8*_K2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (8*_K2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (8*_K2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
              (2*_nx*_phi[_j][_qp]*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms) - 
           _phi[_j][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)));
  }
  else
    return 0.0;
}

Real
AnisotropyUSLLG::computeQpOffDiagJacobian(unsigned int jvar)
{
  if (_component == 0)
  {
    if (jvar == _azimuth_phi_var)
    {
      return ((_g0*(1.0/std::sin(_polar_theta[_qp]))*((-8*_K2*_ny*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
       (8*_K2*_nx*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
       (2*_ny*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
       (2*_nx*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
       (2*_nx*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
       (2*_ny*_phi[_j][_qp]*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
       _alpha*((8*_K2*_ny*_test[_i][_qp]*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
          (2*_test[_i][_qp]*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
          std::cos(_polar_theta[_qp])*((-8*_K2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
             (8*_K2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
             (8*_K2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
             (2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
             (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*Utility::pow<2>(std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
             (2*_ny*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
             (2*_nx*_phi[_j][_qp]*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
             (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_ny*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp]) - _nx*_phi[_j][_qp]*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)));
    }
    else
    {
      return 0.0;
    }
  }
  else if (_component == 1)
  {
    if (jvar == _polar_theta_var)
    {
      return (-((_g0*_phi[_j][_qp]*(std::cos(_polar_theta[_qp])/std::sin(_polar_theta[_qp]))*(1.0/std::sin(_polar_theta[_qp]))*std::sin(_azimuth_phi[_qp])*((2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
          (2*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
          _alpha*((2*_nx*_test[_i][_qp]*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
             std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
                (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
                (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha))) + 
   (_g0*_phi[_j][_qp]*std::cos(_azimuth_phi[_qp])*(std::cos(_polar_theta[_qp])/std::sin(_polar_theta[_qp]))*(1.0/std::sin(_polar_theta[_qp]))*((-2*_nx*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        (2*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        _alpha*((2*_ny*_test[_i][_qp]*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
           std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)) + 
   (_g0*(1.0/std::sin(_polar_theta[_qp]))*std::sin(_azimuth_phi[_qp])*((8*_K2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
        (8*_K2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
        (2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
        (2*_ny*_phi[_j][_qp]*_test[_i][_qp]*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
        (2*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
        (2*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_polar_theta[_qp])*std::sin(_azimuth_phi[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        _alpha*((8*_K2*_nx*_test[_i][_qp]*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
           (2*_nx*_test[_i][_qp]*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
           _phi[_j][_qp]*std::cos(_azimuth_phi[_qp])*std::cos(_polar_theta[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms) + 
           std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-8*_K2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (8*_K2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (8*_K2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_nx*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_polar_theta[_qp])*std::sin(_azimuth_phi[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
              (2*_phi[_j][_qp]*_test[_i][_qp]*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)) - 
   (_g0*std::cos(_azimuth_phi[_qp])*(1.0/std::sin(_polar_theta[_qp]))*((-8*_K2*_nx*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
        (8*_K2*_ny*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
        (2*_nx*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        (2*_nx*_phi[_j][_qp]*_test[_i][_qp]*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        (2*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        (2*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
        _alpha*((8*_K2*_ny*_test[_i][_qp]*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms + 
           (2*_ny*_test[_i][_qp]*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
           _phi[_j][_qp]*std::cos(_polar_theta[_qp])*std::sin(_azimuth_phi[_qp])*((-2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms) + 
           std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*((-8*_K2*_ny*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (8*_K2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (8*_K2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp])))/_Ms - 
              (2*_nx*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_test[_i][_qp]*std::sin(_azimuth_phi[_qp])*std::sin(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_nx*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_azimuth_phi[_qp])*std::cos(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_ny*_phi[_j][_qp]*_test[_i][_qp]*std::cos(_polar_theta[_qp])*std::sin(_azimuth_phi[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1 + 2*_K2*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms - 
              (2*_test[_i][_qp]*std::cos(_polar_theta[_qp])*(_phi[_j][_qp]*std::cos(_polar_theta[_qp])*(_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp])) - _nz*_phi[_j][_qp]*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms + 
              (2*_phi[_j][_qp]*_test[_i][_qp]*std::sin(_polar_theta[_qp])*(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))*(_K1*_nz + 2*_K2*_ny*Utility::pow<2>(_nz*std::cos(_polar_theta[_qp]) + (_nx*std::cos(_azimuth_phi[_qp]) + _ny*std::sin(_azimuth_phi[_qp]))*std::sin(_polar_theta[_qp]))))/_Ms))))/(1 + Utility::pow<2>(_alpha)));
    }
    else
    {
      return 0.0;
    }
  }
  else
    return 0.0;
}
