#!/bin/bash

#PBS -l nodes=1:ppn=16
#PBS -l walltime=48:00:00
#PBS -N PTOhysteresis
#PBS -q msd
#PBS -M john.mangeri@uconn.edu

N_C=`wc -l $PBS_NODEFILE | gawk '//{print $1}'`       # number of CPUs or cores


cd /lcrc/project/Meso/projects/ferret

date

mpiexec -np ${N_C} ./ferret-opt -i 6_PTO_STO_Pole-0.i  > 6_PTO_STO_Pole-0_log

for i in {1..22}; 
do 

mpiexec -np ${N_C} ./ferret-opt -i 6_PTO_STO_NoiseStep-$i.i  > 6_PTO_STO_NoiseStep-$i-_log
mpiexec -np ${N_C} ./ferret-opt -i 6_PTO_STO_Pole-$i.i  > 6_PTO_STO_Pole-$i-_log
	
done

date

